services:
  app1:
    build: .
    environment:
      - APP_NAME=ipclac1
      - PORT=2723
    expose:
      - "2723"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2723/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  
  app2:
    build: .
    environment:
      - APP_NAME=ipclac2
      - PORT=2723
    expose:
      - "2723"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2723/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  app3:
    build: .
    environment:
      - APP_NAME=ipclac3
      - PORT=2723
    expose:
      - "2723"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2723/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  
  nginx:
    image: nginx:latest
    container_name: ip-cidr-calculator-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
      app3:
        condition: service_healthy